### ISSUE TITLE
Tag/release v0.1.0 or v1.0.0

### ISSUE THREAD

**Issue by simnalamburt** [cr0sh/jaso#1]
Then I'll package this program into homebrew, so that users can super easily install this awesome software like this:

```bash
brew install simnalamburt/x/jaso
```

###### Reference
- https://github.com/simnalamburt/homebrew-x/

**Comment by cr0sh** [comment]
[Released](https://github.com/cr0sh/jaso/releases/tag/v0.1.0).

**Comment by simnalamburt** [comment]
@cr0sh 

Now you can install jaso with below:

```bash
brew install simnalamburt/x/jaso
```
