### ISSUE TITLE
`--recursive` option is being ignored, remove.

### ISSUE THREAD

**Issue by simnalamburt** [cr0sh/jaso#3]
I'm willing to send a patch for this issue by myself, and I'm going to ask before I do.

What do you think? Even if we implement this option, I think it would be more usable to leave recursive as a default behavior and add a `--no-recursive` option.

**Comment by cr0sh** [comment]
Agreed, will look on #5. Further improvement about no-recursive option is welcome.

**Comment by simnalamburt** [comment]
I'm considering replaceing the whole directory walking codes with https://github.com/BurntSushi/walkdir/ (I'll do benchmark)

I'm going to implement `--no-recursive` option after that.
