### ISSUE TITLE
Consider chaning main branch name from `master` to `main`

### ISSUE THREAD

**Issue by simnalamburt** [cr0sh/jaso#6]
Consider chaning main branch name from `master` to `main`.

You can easily do this in the settings menu: https://github.com/cr0sh/jaso/settings

<img width="790" alt="image" src="https://github.com/cr0sh/jaso/assets/4435445/882b38f5-34b8-4633-b8ec-9ba1430a4198">

**Comment by cr0sh** [comment]
I'll consider it. Thanks for pointing out.

**Comment by cr0sh** [comment]
Changed the name to `main`.
